### ISSUE TITLE
mdd_loss became float not Tensor

### ISSUE THREAD

**Issue by NRshka** [theislab/trvaep#1]
Got the following error while trying to train the model.
```
Traceback (most recent call last):
  File "trvae.py", line 83, in <module>
    trainer.train_trvae(1)
  File ".../miniconda3/envs/py36/lib/python3.6/site-packages/trvaep/model/train.py", line 130, in train_trvae
    train_mmd += mdd_loss.item()
AttributeError: 'float' object has no attribute 'item'
```

**Comment by NRshka** [comment]
Well, this error is caused by a dataset with only one batch. I don't know is it wrong behavior. I think in this case  there is should be warning wth helpful info or smth.

**Comment by M0hammadL** [comment]
Hey, I guess the problem is set ‘use_mmd=False‘ while you have only one condition and the model turn to a vanilla cvae. The pytorch version is a bit new:) Will be happy to merge your pull requests
