### ISSUE TITLE
Bug with logging

### ISSUE THREAD

**Issue by NRshka** [theislab/trvaep#3]
After several eras an error occurs:
![bug](https://user-images.githubusercontent.com/14370371/74601104-94e7ef80-50cc-11ea-9d99-f30c78a18227.png)
I think the problem is using tensors with format string. I use this dirty hack locally:
![crutch](https://user-images.githubusercontent.com/14370371/74601353-e04fcd00-50cf-11ea-8814-a7c5bbd2d12a.png)
It works for me ad hoc.

**Comment by M0hammadL** [comment]
I think the problem comes from the PyTorch version differencees
