### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by notimenocall** [theislab/trvaep#4]
Hi,
Thanks much for developing the tool! Really love it.
I ran into an error of 'float division by zero' when doing 'trainer.train_trvae(200, 512, early_patience=30)'. Any idea please? Thanks.

`---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-140-07289a4fb3be> in <module>
----> 1 trainer.train_trvae(200, 512, early_patience=30)

~\AppData\Roaming\Python\Python37\site-packages\trvaep\model\train.py in train_trvae(self, n_epochs, batch_size, early_patience)
    120                 vae_loss, reconstruction_loss, kl_loss = MSE_kl(recon_x, x, mean, log_var, self.model.alpha)
    121                 mmd_calculator = mmd(self.model.num_cls, self.model.beta)
--> 122                 mdd_loss = mmd_calculator(y_mmd, y)
    123                 loss = vae_loss + mdd_loss
    124                 optimizer.zero_grad()

~\AppData\Roaming\Python\Python37\site-packages\trvaep\model\_losses.py in mmd_loss(x, y)
     23                 if conditions_mmd[j].size(0) < 2:
     24                     continue
---> 25                 mmd_calculator = MMDStatistic(conditions_mmd[j].size(0), conditions_mmd[j + 1].size(0))
     26                 loss += mmd_calculator(conditions_mmd[j], conditions_mmd[j + 1], alphas=alphas)
     27         return beta * loss

~\AppData\Roaming\Python\Python37\site-packages\trvaep\model\utiil.py in __init__(self, n_1, n_2)
     60         # The three constants used in the test.
     61         self.a00 = 1. / (n_1 * (n_1 - 1))
---> 62         self.a11 = 1. / (n_2 * (n_2 - 1))
     63         self.a01 = - 1. / (n_1 * n_2)
     64 

ZeroDivisionError: float division by zero`

**Comment by M0hammadL** [comment]
Hi. The batch size should increases when getting an error like that.
